version: '3'

services:
  lp:
    image: docker.prohibet.com/sss-list-provider:latest
    labels:
      - "com.centurylinklabs.watchtower.enable=true"
    ports:
      - 8102:8002
    volumes:
      - list-provider-data:/sss/client/list_provider/data/
      - ${SSS_ENV_VAR}/list_provider:/sss/client/list_provider/creds
    networks:
      - prohibet_network
    restart: always

  watchtower:
    image: docker.prohibet.com/containrrr/watchtower
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
      - ${SSS_ENV_VAR}/watchtower/config.json:/config.json
    command: --http-api-update --cleanup
    environment:
      - WATCHTOWER_HTTP_API_TOKEN=0ocqwe8Y@ocswc!N
      - WATCHTOWER_CLEANUP=true
    labels:
      - "com.centurylinklabs.watchtower.enable=false"
    ports:
      - 8080:8080
    networks:
      - prohibet_network
    restart: always

networks:
  prohibet_network:
    driver: bridge

volumes:
  list-provider-data:
